In [1]:
!pip install funpymodeling

Requirement already satisfied: funpymodeling in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (0.1.9)
Requirement already satisfied: flake8<7.0.0,>=6.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (6.1.0)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (1.0.0)
Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (3.9.0)
Requirement already satisfied: numpy<2.0.0,>=1.26.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=2.1.4 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (2.2.2)
Requirement already satisfied: pre-commit<4.0.0,>=3.3.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (3.8.0)
Requirement already satisfied: pytest<8.0.0,>=7.3.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (7.4.4)
Requirement already satisfied: scikit-learn<2.0.0,>=1.2.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (1.5.1)
Requirement already satisfied: seaborn<0.13.0,>=0.12.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (0.12.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.6.3 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from funpymodeling) (4.12.2)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from flake8<7.0.0,>=6.0.0->funpymodeling) (0.7.0)
Requirement already satisfied: pycodestyle<2.12.0,>=2.11.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from flake8<7.0.0,>=6.0.0->funpymodeling) (2.11.1)
Requirement already satisfied: pyflakes<3.2.0,>=3.1.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from flake8<7.0.0,>=6.0.0->funpymodeling) (3.1.0)
Requirement already satisfied: notebook in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (7.2.1)
Requirement already satisfied: qtconsole in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (5.5.2)
Requirement already satisfied: jupyter-console in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (7.16.4)
Requirement already satisfied: ipykernel in c:\users\dave\appdata\roaming\python\python312\site-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (6.29.5)
Requirement already satisfied: ipywidgets in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (8.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\dave\appdata\roaming\python\python312\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dave\appdata\roaming\python\python312\site-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pandas<3.0.0,>=2.1.4->funpymodeling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pandas<3.0.0,>=2.1.4->funpymodeling) (2024.1)
Requirement already satisfied: cfgv>=2.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (3.4.0)
Requirement already satisfied: identify>=1.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (2.6.0)
Requirement already satisfied: nodeenv>=0.11.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (1.9.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (6.0.1)
Requirement already satisfied: virtualenv>=20.10.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (20.26.3)
Requirement already satisfied: iniconfig in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pytest<8.0.0,>=7.3.1->funpymodeling) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from pytest<8.0.0,>=7.3.1->funpymodeling) (1.5.0)
Requirement already satisfied: colorama in c:\users\dave\appdata\roaming\python\python312\site-packages (from pytest<8.0.0,>=7.3.1->funpymodeling) (0.4.6)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn<2.0.0,>=1.2.2->funpymodeling) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn<2.0.0,>=1.2.2->funpymodeling) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn<2.0.0,>=1.2.2->funpymodeling) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\dave\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.7.1->funpymodeling) (1.16.0)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.10.0->pre-commit<4.0.0,>=3.3.2->funpymodeling) (0.3.8)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.10.0->pre-commit<4.0.0,>=3.3.2->funpymodeling) (3.15.4)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\dave\appdata\roaming\python\python312\site-packages (from virtualenv>=20.10.0->pre-commit<4.0.0,>=3.3.2->funpymodeling) (4.2.2)
Requirement already satisfied: comm>=0.1.1 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.8.5)
Requirement already satisfied: ipython>=7.23.1 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (8.26.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (8.6.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.6.0)
Requirement already satisfied: psutil in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (6.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (26.1.0)
Requirement already satisfied: tornado>=6.1 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.11 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.0.11)
Requirement already satisfied: jupyterlab-widgets~=3.0.11 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.11)
Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\users\dave\appdata\roaming\python\python312\site-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.47)
Requirement already satisfied: pygments in c:\users\dave\appdata\roaming\python\python312\site-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.18.0)
Requirement already satisfied: beautifulsoup4 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (6.1.0)
Requirement already satisfied: defusedxml in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.1.4)
Requirement already satisfied: jupyterlab-pygments in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.1.5)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.10.0)
Requirement already satisfied: nbformat>=5.7 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.5.1)
Requirement already satisfied: tinycss2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.14.2)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.27.3)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.2.4)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.4)
Requirement already satisfied: qtpy>=2.4.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from qtconsole->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.4.1)
Requirement already satisfied: webencodings in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.5.1)
Requirement already satisfied: decorator in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.19.1)
Requirement already satisfied: stack-data in c:\users\dave\appdata\roaming\python\python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.6.3)
Requirement already satisfied: pywin32>=300 in c:\users\dave\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (306)
Requirement already satisfied: anyio>=3.1.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.4.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (23.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.5.3)
Requirement already satisfied: overrides>=5.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.20.0)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.0.13)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.27.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.2.5)
Requirement already satisfied: setuptools>=40.1.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (72.1.0)
Requirement already satisfied: babel>=2.10 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.15.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.9.25)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.20.0)
Requirement already satisfied: wcwidth in c:\users\dave\appdata\roaming\python\python312\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.13)
Requirement already satisfied: soupsieve>1.2 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.5)
Requirement already satisfied: idna>=2.8 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (21.2.0)
Requirement already satisfied: certifi in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2024.7.4)
Requirement already satisfied: httpcore==1.* in c:\users\dave\appdata\local\programs\python\python312\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.0.5)

In [2]:
import pandas as pd
from funpymodeling import status

customer_file = '../data/customers.json'
df_json_nested = pd.read_json(customer_file, lines= True)

In [3]:
from pandas import json_normalize

customers_df = json_normalize(df_json_nested['customer'])

customers_df.head(3)

,customerEmail,customerPhone,customerDevice,customerIPAddress,customerBillingAddress
0,josephhoward@yahoo.com,400-108-5415,yyeiaxpltf82440jnb3v,8.129.104.40,"5493 Jones Islands\nBrownside, CA 51896"
1,evansjeffery@yahoo.com,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,219.173.211.202,356 Elizabeth Inlet Suite 120\nPort Joshuabury...
2,andersonwilliam@yahoo.com,024.420.0375,4m7h5ipl1shyavt6vv2r,67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250"

In [4]:
orders_nested = pd.DataFrame([md for md in df_json_nested["orders"]])

orders_list = []

for index, row in orders_nested.iterrows():
    for order in row:
        if order != None:
            orders_list.append(order)

orders_df = pd.DataFrame(orders_list)

orders_df.head(3)

,orderId,orderAmount,orderState,orderShippingAddress
0,vjbdvd,18,pending,"5493 Jones Islands\nBrownside, CA 51896"
1,yp6x27,26,fulfilled,"5493 Jones Islands\nBrownside, CA 51896"
2,nlghpa,45,fulfilled,"898 Henry Ports\nNew Keithview, CA 95893-2497"

In [5]:
transactions_nested = pd.DataFrame([md for md in df_json_nested["transactions"]])

transactions_list=[]
for index,row in transactions_nested.iterrows():
    for transaction in row:
        if transaction != None:
            transactions_list.append(transaction)           
transactions_df = pd.DataFrame(transactions_list)

transactions_df.head(3)

  transactionId orderId paymentMethodId  transactionAmount  transactionFailed
0      a9lcj51r  vjbdvd       wt07xm68b                 18              False
1      y4wcv03i  yp6x27       wt07xm68b                 26              False
2      5mi94sfw  nlghpa       41ug157xz                 45              False

In [6]:
payment_nested = pd.DataFrame([md for md in df_json_nested["paymentMethods"]])

payment_methods_list=[]
for index,row in payment_nested.iterrows():
    for order in row:
        if order != None:
            payment_methods_list.append(order)           
payment_methods_df = pd.DataFrame(payment_methods_list)

payment_methods_df.head(3)

,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer
0,wt07xm68b,True,card,JCB 16 digit,Citizens First Banks
1,y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks
2,6krszxc05,False,card,VISA 16 digit,Vertex Bancorp

In [7]:
fraudulent_df = df_json_nested['fraudulent']

In [8]:
data = pd.concat([customers_df, orders_df, payment_methods_df, transactions_df, fraudulent_df], axis=1)

data.head(10)

,customerEmail,customerPhone,customerDevice,customerIPAddress,customerBillingAddress,orderId,orderAmount,orderState,orderShippingAddress,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer,transactionId,orderId,paymentMethodId,transactionAmount,transactionFailed,fraudulent
0,josephhoward@yahoo.com,400-108-5415,yyeiaxpltf82440jnb3v,8.129.104.40,"5493 Jones Islands\nBrownside, CA 51896",vjbdvd,18.0,pending,"5493 Jones Islands\nBrownside, CA 51896",wt07xm68b,True,card,JCB 16 digit,Citizens First Banks,a9lcj51r,vjbdvd,wt07xm68b,18,False,False
1,evansjeffery@yahoo.com,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,219.173.211.202,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,yp6x27,26.0,fulfilled,"5493 Jones Islands\nBrownside, CA 51896",y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks,y4wcv03i,yp6x27,wt07xm68b,26,False,True
2,andersonwilliam@yahoo.com,024.420.0375,4m7h5ipl1shyavt6vv2r,67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",nlghpa,45.0,fulfilled,"898 Henry Ports\nNew Keithview, CA 95893-2497",6krszxc05,False,card,VISA 16 digit,Vertex Bancorp,5mi94sfw,nlghpa,41ug157xz,45,False,False
3,rubenjuarez@yahoo.com,670.664.8168x94985,slovx60t0i558may4ks0,95de:8565:5a66:792c:26e0:6cfb:7d87:11af,"7769 Elizabeth Bridge Apt. 343\nNortonstad, FM...",uw0eeb,23.0,fulfilled,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,5z1szj2he,False,card,Diners Club / Carte Blanche,His Majesty Bank Corp.,br8ba1nu,uw0eeb,41ug157xz,23,False,False
4,uchen@malone.com,1-981-877-0870,j0pd24k5h8dl2fqu0cz4,196.89.235.192,"148 Russell Lodge Apt. 445\nPort Jenniferside,...",bn44oh,43.0,fulfilled,"5093 Bryan Forks\nJoshuaton, FM 01565-9801",m52tx8e1s,False,card,Mastercard,Vertex Bancorp,a33145ss,bn44oh,y3xp697jx,43,True,True
5,robinsoncynthia@dunn.com,+65(5)8997489788,hbww39m1wenbq4ymjhsx,43.166.163.164,"65233 Hutchinson Mountains\nMartinezside, OR 7...",yk34y2,33.0,failed,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",41ug157xz,False,bitcoin,American Express,Bastion Banks,q3lyvbza,yk34y2,8pneoi03z,33,False,True
6,samuel15@saunders-rhodes.com,05045239487,up7afvce5v0omniqlevq,33.67.35.30,"3960 Emily Fort\nStaceytown, AR 21817-3325",28v6b0,24.0,fulfilled,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",4dpg5sx2b,False,card,Maestro,Her Majesty Trust,3alf9irw,28v6b0,8pneoi03z,24,True,True
7,johnlowery@gmail.com,044-642-9860,rjb0adai34izqvys4938,212.144.68.190,"484 Pamela Pass\nLake Jessicaview, WI 12942-9074",itnk8y,25.0,fulfilled,"22396 Victor Lights\nCarsonstad, MO 93914",bcx9pa3wf,False,card,JCB 16 digit,Fountain Financial Inc.,69w9wymx,28v6b0,8pneoi03z,24,False,True
8,jameslandry@rodriguez.com,1-885-168-1310x338,yz4l2bgbvzra5eb5qcan,c899:ff67:6864:4365:def3:3023:655f:5181,USNS Price\nFPO AE 14661,fbz9ep,34.0,fulfilled,"7769 Elizabeth Bridge Apt. 343\nNortonstad, FM...",8pneoi03z,False,card,JCB 16 digit,Bastion Banks,pegqc4ud,itnk8y,dluy3jka0,25,True,False
9,ubranch@rivera-parker.info,(772)964-8162x6310,6mpx027neyz6sh04n3ue,86.16.65.228,"6974 Robertson Common Apt. 902\nPort Juanside,...",7odnn6,26.0,fulfilled,"7769 Elizabeth Bridge Apt. 343\nNortonstad, FM...",dluy3jka0,False,card,Discover,His Majesty Bank Corp.,uo3slwh7,itnk8y,8pneoi03z,25,False,True

In [9]:
status(data)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,customerEmail,455,0.730337,0,0.000000,161,object
1,customerPhone,455,0.730337,0,0.000000,168,object
2,customerDevice,455,0.730337,0,0.000000,168,object
3,customerIPAddress,455,0.730337,0,0.000000,165,object
4,customerBillingAddress,455,0.730337,0,0.000000,166,object
5,orderId,145,0.232745,0,0.000000,478,object
6,orderAmount,145,0.232745,0,0.000000,67,float64
7,orderState,145,0.232745,0,0.000000,3,object
8,orderShippingAddress,145,0.232745,0,0.000000,274,object
9,paymentMethodId,281,0.451043,0,0.000000,342,object
10,paymentMethodRegistrationFailure,281,0.451043,302,0.484751,2,object
11,paymentMethodType,281,0.451043,0,0.000000,4,object
12,paymentMethodProvider,281,0.451043,0,0.000000,10,object
13,paymentMethodIssuer,281,0.451043,0,0.000000,20,object
14,transactionId,0,0.000000,0,0.000000,623,object
15,orderId,0,0.000000,0,0.000000,478,object
16,paymentMethodId,0,0.000000,0,0.000000,237,object
17,transactionAmount,0,0.000000,0,0.000000,67,int64
18,transactionFailed,0,0.000000,455,0.730337,2,bool
19,fraudulent,455,0.730337,107,0.171750,2,object

In [10]:
data = data.loc[:,~data.columns.duplicated()].copy()

status(data)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,customerEmail,455,0.730337,0,0.000000,161,object
1,customerPhone,455,0.730337,0,0.000000,168,object
2,customerDevice,455,0.730337,0,0.000000,168,object
3,customerIPAddress,455,0.730337,0,0.000000,165,object
4,customerBillingAddress,455,0.730337,0,0.000000,166,object
5,orderId,145,0.232745,0,0.000000,478,object
6,orderAmount,145,0.232745,0,0.000000,67,float64
7,orderState,145,0.232745,0,0.000000,3,object
8,orderShippingAddress,145,0.232745,0,0.000000,274,object
9,paymentMethodId,281,0.451043,0,0.000000,342,object
10,paymentMethodRegistrationFailure,281,0.451043,302,0.484751,2,object
11,paymentMethodType,281,0.451043,0,0.000000,4,object
12,paymentMethodProvider,281,0.451043,0,0.000000,10,object
13,paymentMethodIssuer,281,0.451043,0,0.000000,20,object
14,transactionId,0,0.000000,0,0.000000,623,object
15,transactionAmount,0,0.000000,0,0.000000,67,int64
16,transactionFailed,0,0.000000,455,0.730337,2,bool
17,fraudulent,455,0.730337,107,0.171750,2,object

In [11]:
email_domains= []
mails= []
popular_providers = ['yahoo', 'gmail', 'hotmail']

for email in data['customerEmail']:
    try:
        """
        Si email = "edvai@yahoo.com"

        aux = yahoo.com
        mail = yahoo
        domain = com
        """
        aux = email.split('@')[1]
        domain = aux.split('.')[1]
        mail = aux.split('.')[0]
        
        if mail in popular_providers:
            mails.append(mail)
        else:
            mails.append('other')
        email_domains.append(domain)
        
    except:
        email_domains.append('weird')
        mails.append('weird')
        # print(email)

data['emailProvider'] = mails
data['emailDomain'] = email_domains

data = data.drop(['customerEmail'], axis=1)

data.head(3)

,customerPhone,customerDevice,customerIPAddress,customerBillingAddress,orderId,orderAmount,orderState,orderShippingAddress,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer,transactionId,transactionAmount,transactionFailed,fraudulent,emailProvider,emailDomain
0,400-108-5415,yyeiaxpltf82440jnb3v,8.129.104.40,"5493 Jones Islands\nBrownside, CA 51896",vjbdvd,18.0,pending,"5493 Jones Islands\nBrownside, CA 51896",wt07xm68b,True,card,JCB 16 digit,Citizens First Banks,a9lcj51r,18,False,False,yahoo,com
1,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,219.173.211.202,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,yp6x27,26.0,fulfilled,"5493 Jones Islands\nBrownside, CA 51896",y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks,y4wcv03i,26,False,True,yahoo,com
2,024.420.0375,4m7h5ipl1shyavt6vv2r,67b7:3db8:67e0:3bea:b9d0:90c1:2b60:b9f0,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",nlghpa,45.0,fulfilled,"898 Henry Ports\nNew Keithview, CA 95893-2497",6krszxc05,False,card,VISA 16 digit,Vertex Bancorp,5mi94sfw,45,False,False,yahoo,com

In [12]:
IP_addresses = []
for address in data['customerIPAddress']:

    # A veces lo toma como flotante al address
    aux_address = str(address)
    
    if len(aux_address) > 15:
        IP_addresses.append('digits_and_letters')
    else:
        IP_addresses.append('only_letters')

data['customerIPAddressSimplified'] = IP_addresses

data = data.drop(['customerIPAddress'], axis=1)

data.head(3)

,customerPhone,customerDevice,customerBillingAddress,orderId,orderAmount,orderState,orderShippingAddress,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer,transactionId,transactionAmount,transactionFailed,fraudulent,emailProvider,emailDomain,customerIPAddressSimplified
0,400-108-5415,yyeiaxpltf82440jnb3v,"5493 Jones Islands\nBrownside, CA 51896",vjbdvd,18.0,pending,"5493 Jones Islands\nBrownside, CA 51896",wt07xm68b,True,card,JCB 16 digit,Citizens First Banks,a9lcj51r,18,False,False,yahoo,com,only_letters
1,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,yp6x27,26.0,fulfilled,"5493 Jones Islands\nBrownside, CA 51896",y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks,y4wcv03i,26,False,True,yahoo,com,only_letters
2,024.420.0375,4m7h5ipl1shyavt6vv2r,"8478 Sean Ridges Apt. 441\nDavisberg, PR 72250",nlghpa,45.0,fulfilled,"898 Henry Ports\nNew Keithview, CA 95893-2497",6krszxc05,False,card,VISA 16 digit,Vertex Bancorp,5mi94sfw,45,False,False,yahoo,com,digits_and_letters

In [13]:
def extract_city_name(name_column):
    city_list = []

    for address in data[name_column]:
        try:
            """
            Si address = "5493 Jones Islands\nBrownside, CA 51896"

            aux = "Brownside, CA 51896"
            city_with_number = "CA 51896"
            city = "CA"
            """
            aux = address.split('\n')[1]
            city_with_number = aux.split(', ')[1]
            city = city_with_number.split(' ')[0]
            
            city_list.append(city)
                
        except:
            # Sino aparece el nombre de la ciudad asignamos: unknown
            city_list.append("unknown")
    
    return city_list

data["customerBillingAddress"] = extract_city_name("customerBillingAddress")
data["orderShippingAddress"] = extract_city_name("orderShippingAddress")

data.head(3)

,customerPhone,customerDevice,customerBillingAddress,orderId,orderAmount,orderState,orderShippingAddress,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer,transactionId,transactionAmount,transactionFailed,fraudulent,emailProvider,emailDomain,customerIPAddressSimplified
0,400-108-5415,yyeiaxpltf82440jnb3v,CA,vjbdvd,18.0,pending,CA,wt07xm68b,True,card,JCB 16 digit,Citizens First Banks,a9lcj51r,18,False,False,yahoo,com,only_letters
1,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,NM,yp6x27,26.0,fulfilled,CA,y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks,y4wcv03i,26,False,True,yahoo,com,only_letters
2,024.420.0375,4m7h5ipl1shyavt6vv2r,PR,nlghpa,45.0,fulfilled,CA,6krszxc05,False,card,VISA 16 digit,Vertex Bancorp,5mi94sfw,45,False,False,yahoo,com,digits_and_letters

In [14]:
same_city = []

for index in range(len(data)):
    billing_address = data["customerBillingAddress"][index]
    order_address = data["orderShippingAddress"][index]

    response = "unknown"
    if billing_address != "unknown" and order_address != "unknown":
        if billing_address == order_address:
            response = "yes"
        else:
            response = "no"
    
    same_city.append(response)

data["sameCity"] = same_city

data = data.drop(["customerBillingAddress", "orderShippingAddress"], axis = 1)

data.head(3)

,customerPhone,customerDevice,orderId,orderAmount,orderState,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer,transactionId,transactionAmount,transactionFailed,fraudulent,emailProvider,emailDomain,customerIPAddressSimplified,sameCity
0,400-108-5415,yyeiaxpltf82440jnb3v,vjbdvd,18.0,pending,wt07xm68b,True,card,JCB 16 digit,Citizens First Banks,a9lcj51r,18,False,False,yahoo,com,only_letters,yes
1,1-788-091-7546,r0jpm7xaeqqa3kr6mzum,yp6x27,26.0,fulfilled,y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks,y4wcv03i,26,False,True,yahoo,com,only_letters,no
2,024.420.0375,4m7h5ipl1shyavt6vv2r,nlghpa,45.0,fulfilled,6krszxc05,False,card,VISA 16 digit,Vertex Bancorp,5mi94sfw,45,False,False,yahoo,com,digits_and_letters,no

In [15]:
data = data.drop(['customerPhone'], axis=1)
data = data.drop(['customerDevice', 'orderId', 'transactionId', 'paymentMethodId'], axis=1)

data.head(3)

,orderAmount,orderState,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer,transactionAmount,transactionFailed,fraudulent,emailProvider,emailDomain,customerIPAddressSimplified,sameCity
0,18.0,pending,True,card,JCB 16 digit,Citizens First Banks,18,False,False,yahoo,com,only_letters,yes
1,26.0,fulfilled,True,bitcoin,VISA 16 digit,Solace Banks,26,False,True,yahoo,com,only_letters,no
2,45.0,fulfilled,False,card,VISA 16 digit,Vertex Bancorp,45,False,False,yahoo,com,digits_and_letters,no

In [16]:
status(data)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,orderAmount,145,0.232745,0,0.000000,67,float64
1,orderState,145,0.232745,0,0.000000,3,object
2,paymentMethodRegistrationFailure,281,0.451043,302,0.484751,2,object
3,paymentMethodType,281,0.451043,0,0.000000,4,object
4,paymentMethodProvider,281,0.451043,0,0.000000,10,object
5,paymentMethodIssuer,281,0.451043,0,0.000000,20,object
6,transactionAmount,0,0.000000,0,0.000000,67,int64
7,transactionFailed,0,0.000000,455,0.730337,2,bool
8,fraudulent,455,0.730337,107,0.171750,2,object
9,emailProvider,0,0.000000,0,0.000000,5,object
10,emailDomain,0,0.000000,0,0.000000,6,object
11,customerIPAddressSimplified,0,0.000000,0,0.000000,2,object
12,sameCity,0,0.000000,0,0.000000,3,object

In [17]:
filename = "../data/customer_dataset.csv"
data.to_csv(filename, index = False)